### ISSUE TITLE
Error when plotting light curves

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#3]
Hi Nestor.

I've gotten the following error when plotting the photometry of a fit, similar to the phase folded RV problem:

/Users/jvines/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:3250: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
/Users/jvines/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "juliet.py", line 2412, in <module>
    * 7.5, np.max(omedian_model) + np.max(ferr_instrument) * 7.5])
  File "/Users/jvines/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3457, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/Users/jvines/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3068, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

Cheers.

**Comment by nespinoza** [comment]
Hi @jvines,

 Are you by any chance using a GP on the photometry? And if so --- which GP kernel?

N.

**Comment by jvines** [comment]
Hi Nestor,

I am using GP on the photometry. I'm using the exponential kernel from celerite

**Comment by nespinoza** [comment]
Hi @jvines,

 This might be the problem. I have an open issue in celerite (https://github.com/dfm/celerite/issues/141) because it sometimes spits out "Nan" values, which is most likely what you are seeing here. To check this, in the .dat files outputted by juliet, do you see Nan values?

 Best

Néstor

**Comment by jvines** [comment]
Hi Néstor,

Indeed that is the case, the are nan values in the output files.

Cheers

**Comment by nespinoza** [comment]
Hi @jvines,

 Sadly we will have to wait until a patch comes up for this in `celerite`. What I can say, however, is that this is a plotting issue only and the posterior fits should be OK (at least, I've ran tests and the posteriors I get are exactly what I put in). In any case, I'll keep you updated on any news regarding `celerite`.

I'll leave this issue open so I remember to come back to this once Dan Foreman-Mackey can shine some light on why this issue is appearing!

N.

**Comment by jvines** [comment]
Hi @nespinoza,

Playing around with Juliet I found that, rather randomly, the GP returns only nan values (resulting in a phase folded plot with only the model, but not the data). Every other thing works fine, except that plot.

Looking at the code I managed to find that the first instance of the GPmodel variable printed nan values, but I couldn't go further.

I say it occurs rather randomly because I've re-run Juliet to find that it works, or that it doesn't.

I'm using the mattern * exp kernel from celerite.

Cheers,

Jose V

**Comment by dianadianadiana** [comment]
Hi all, 

To do a quick "go around" this issue, I implemented this change found in this commit: 18606e48d274f2abc963361288729027098281e1
The root problem isn't fixed, but now we are able to obtain the automatic juliet plots.

Essentially, for some samples, there might be one value in the computed GP model that contains a NaN value. If this is the case, we don't consider this sample and continue to the next. Based on some examples that we dealt with, the number of samples with bad GP models are rare (occurring 3 out of 500 samples or so). That is why *sometimes* you can do a juliet rerun and it will work, and other times it does not. It just depends if you were lucky enough to avoid these NaN values.

Since the problem of the NaNs still exists (because of celerite as @nespinoza mentioned), I won't close this issue.
