### ISSUE TITLE
First import fails

### ISSUE THREAD

**Issue by mileslucas** [nespinoza/juliet#53]
First import of this package off a clean import fails due to not all dependencies being listed in https://github.com/nespinoza/juliet/blob/763f49c495b36d78e7bb1ae75976a5707287f265/setup.py#L21

From a clean docker container, 
```
$ pip install juliet
```
```python
>>> import juliet
[...]
ModuleNotFoundError: No module named 'h5py'
```
after manually installing `h5py` import works fine. It seems like adding h5py to the `install_requires` would fix the pip installation

**Comment by nespinoza** [comment]
Hi @mileslucas,

 Thanks a lot for letting us know about this. It turns out `h5py` is not really a dependency of `juliet`, but of `radvel` (which `juliet` uses). Recently, `radvel` removed this from their list of dependencies (see: https://github.com/California-Planet-Search/radvel/commit/117d4e6946c73a9b739108da64a891732f9c669b) so perhaps this is causing the issue. 

 Could you confirm that installing `radvel` in a clean import reproduces this error? You would follow the same steps (`pip install radevel`, then `import radvel`). If that is the case, we might want to reach out to the `radvel` developers --- perhaps @bjfultn has some input here as well.

 Thanks!
Néstor

**Comment by mileslucas** [comment]
thanks for looking into this, it does appear to be isolated to `radvel`. I'll close this issue and open one over there!
