### ISSUE TITLE
Fitting progress got stuck

### ISSUE THREAD

**Issue by MoneSylvia** [nespinoza/juliet#68]
Hello!

So basically I have this transit data and some priors. I tried to run the fit with both `PyMultinest` and `dynesty` and it got stuck at some point (e.g. picture attached below; it got stuck at minute 14:58). At first, I thought it was my internet connection or my device's memory problem but I've tried to run the same fit on four different devices and it still got stuck.

![Screenshot from 2021-09-11 22-42-29](https://user-images.githubusercontent.com/89698848/132970945-a6240813-8913-4bd3-baff-0a88977bbacc.png)

So I assume the problem is my priors but they are pretty normal, I guess (?) Below I attached my transit data and the priors in case they are indeed NOT normal (e.g. too wide etc.):

[TOI1062_lc.txt](https://github.com/nespinoza/juliet/files/7148933/TOI1062_lc.txt)
[priors.txt](https://github.com/nespinoza/juliet/files/7149320/priors.txt)

I tried to change `sesinomega` and `secosomega` to `ecc` and `omega` with a fixed value of 0. and 90. and turned out the fit worked and was done. 
I also tried to run the example code in the [documentation](https://juliet.readthedocs.io/en/latest/tutorials/transitfits.html#transit-fits) but the `ecc` and `omega` parameter were changed to `sesinomega` and `secosomega` with a uniform distribution from -1 to 1. Turned out the fit got stuck as well.

The fit for radial velocity data seems doesn't have this problem. I encounter it only for transit data.

I really have no idea to whatever caused the problem. Any help will greatly appreciated!

Best,
Sylvia

**Comment by dianadianadiana** [comment]
Hey Sylvia!

Yes that sounds frustrating. Taking a look at the problem and the priors, this is what I would try next:

(1) improve the priors a bit
`sigma_w_TESS` J(0.1,1000.0) —> J(1e-08,1e3) — just in case your TESS data doesn’t need to be that noisy — I typically have it from 1e-08 for my runs
`t0_p1` U(2458300.0,2458400.0) —> this prior range is 100d wide! So if your planet is on an orbit of 4-5d, multiple t0 values (~20-25) will be picked up in the posterior. So I suggest taking the last transit event (I tried but couldn’t easily find it by eye) and centering t0 around there. So let’s say the center of the last observable transit is at 2458390, then apply a prior like, U(2458387.5,2458392.5)

(2) apply `ecclim`
When you do `results = dataset.fit(…)` also include the keyword `ecclim=0.8` (or any maximum eccentricity you would like to impose).
This might be the issue where when you have no limit on the eccentricity, it could be that samples tend to a higher eccentricity and then the sampler can get stuck there (depending on the data quality of your LC). 
You said you fixed `ecc` and `omega` to 0 and 90, but did you also try fixing `sesinomega` and `secosomega` to 0 and 0 and also get a successful run? I would hope it gives the same results

These are the things that I would immediately try to see if the problem is fixed, but let us know if it helps or still persists :)

Best,
Diana

**Comment by MoneSylvia** [comment]
It worked! For both alternatives. Thanks a lot! So my priors are indeed too wide and I should constrain them to a more specific value, especially the eccentricity I guess..

Best,
Slyvia

**Comment by nespinoza** [comment]
Just to be clear on the eccentricity problem --- this is a `batman` issue really (the lightcurve model we use). The solver of the Kepler equation gets stuck at values too close to eccentricity equal to 1 with the standard setup of the base code.

**Comment by MoneSylvia** [comment]
Ah I see. It really makes sense since I encounter this problem only for transit fitting. I don't have any problem at all when fitting radial velocity data since setting `sesinomega` and `secosomega` with uniform distribution U[-1,1] worked really fine for me.
