### ISSUE TITLE
load pickle file

### ISSUE THREAD

**Issue by zmberdinas** [nespinoza/juliet#7]
The documentation (section "Installing and basic usage/juliet outputs") indicates that the posteriors can be read as:
`posteriors = pickle.load(open('posteriors.pkl','r'))`
However, the pickle file was encoding as a binary file, thus, I have to read as:
`posteriors = pickle.load(open('posteriors.pkl','rb'))`
Maybe you would want to update the documentation if this is a general case.

**Comment by dianadianadiana** [comment]
Hi @zmberdinas,

Thanks for pointing this out! This is now fixed in the Wiki. In the juliet.py file, we had 'rb' so nothing was changed there, but I did add a different way of reading the pickle file because I encountered an issue myself, see commit: 110ae8125744a8d0835dfee6d7a1f585b60f25f0
I'll close this issue.

Best,
Diana
