### ISSUE TITLE
Error when output path is too long. 

### ISSUE THREAD

**Issue by zmberdinas** [nespinoza/juliet#9]
Hi Diana and Nestor! 
  I've got an error in line #1310 when reading "posterior_samples".  

 #1309     output = pymultinest.Analyzer(outputfiles_basename=out_file, n_params = n_params)
 #1309     # Get out parameters: this matrix has (samples,n_params+1):
 #1310     posterior_samples = output.get_equal_weighted_posterior()[:,:-1]

Basically, Juliet cannot read Multinest outputs because the file with the largest name created by it inside the output directory has an uncompleted name. This happens when the name given of the output directory is too large. That is, if the -ofolder folder has a large name, e.g. "out_joint_dataset2_k1", Multinest creates something like
"out_multinest_post_equal_weight" instead of "out_multinest_post_equal_weights.dat". Thus, Juliet fails in line 1310 because it can't find Multinest files. I understand this is bug to be solve in pyMultinest, but maybe you could indicate that there is a maximum number of characters for the output directory.

Cheers,
Zaira.

**Comment by nespinoza** [comment]
Hi @zmberdinas --- sorry for answering to this *so late*. This is a problem only with MultiNest, and is actually a problem we cannot solve because the character limit is embedded within MultiNest (see https://github.com/JohannesBuchner/PyMultiNest/issues/107). I have added a warning of this on the documentation though (see https://juliet.readthedocs.io/en/latest/user/quicktest.html).

Thanks!

N.
